-- Teach the built-in /room command the room's shape.
--
-- `create` gains `visibility` (public/private) and `voice` (open/ptt/listen);
-- both are optional, and an omitted one falls through to the preset default.
-- The preset also decides whether a member's choice counts at all, so these
-- options are an offer, not an override.
--
-- `mute` and `unmute` are new subcommands: in a listen-only room they are how
-- the owner hands out the microphone.
--
-- 0061 inserted this row with INSERT OR IGNORE, so it exists. Updating rather
-- than re-inserting keeps every guild's built_in_command_overrides row (their
-- enable/disable and permission gate) pointing at the same command id.

UPDATE commands
SET options = '[{"name":"create","description":"Make your own room","type":1,"options":[{"name":"name","description":"What to call it","type":3,"required":false},{"name":"limit","description":"Max people (voice rooms, 0 = no limit)","type":4,"required":false,"min_value":0,"max_value":99},{"name":"visibility","description":"Who can see and join it","type":3,"required":false,"choices":[{"name":"Private \u2014 only people you invite","value":"private"},{"name":"Public \u2014 anyone can see and join","value":"public"}]},{"name":"voice","description":"How talking works in there","type":3,"required":false,"choices":[{"name":"Open mic","value":"open"},{"name":"Push to talk","value":"ptt"},{"name":"Listen only \u2014 you hand out the mic","value":"listen"}]}]},{"name":"rename","description":"Rename your room","type":1,"options":[{"name":"name","description":"The new name","type":3,"required":true}]},{"name":"invite","description":"Let someone into your room","type":1,"options":[{"name":"user","description":"Who to let in","type":6,"required":true}]},{"name":"kick","description":"Remove someone from your room","type":1,"options":[{"name":"user","description":"Who to remove","type":6,"required":true}]},{"name":"mute","description":"Take someone''s microphone away","type":1,"options":[{"name":"user","description":"Who to mute","type":6,"required":true}]},{"name":"unmute","description":"Give someone the microphone","type":1,"options":[{"name":"user","description":"Who to unmute","type":6,"required":true}]},{"name":"lock","description":"Only invited people can get in","type":1},{"name":"unlock","description":"Back to the default access","type":1},{"name":"limit","description":"Set how many people can be in your room","type":1,"options":[{"name":"limit","description":"0 to 99, where 0 means no limit","type":4,"required":true,"min_value":0,"max_value":99}]},{"name":"transfer","description":"Hand your room to someone else","type":1,"options":[{"name":"user","description":"The new owner","type":6,"required":true}]},{"name":"extend","description":"Keep your room around a while longer","type":1},{"name":"delete","description":"Close your room now","type":1}]',
    action_config = '{"actions":[{"type":"CREATE_MANAGED_CHANNEL","group":"create","condition":{"mode":"if_equals","option":"__subcommand","value":"create"},"config":{"name":"{option.name}","user_limit":"option:limit","visibility":"{option.visibility}","voice_mode":"{option.voice}"}},{"type":"MANAGE_MANAGED_CHANNEL","group":"rename","condition":{"mode":"if_equals","option":"__subcommand","value":"rename"},"config":{"verb":"rename","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"invite","condition":{"mode":"if_equals","option":"__subcommand","value":"invite"},"config":{"verb":"invite","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"kick","condition":{"mode":"if_equals","option":"__subcommand","value":"kick"},"config":{"verb":"kick","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"mute","condition":{"mode":"if_equals","option":"__subcommand","value":"mute"},"config":{"verb":"mute","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"unmute","condition":{"mode":"if_equals","option":"__subcommand","value":"unmute"},"config":{"verb":"unmute","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"lock","condition":{"mode":"if_equals","option":"__subcommand","value":"lock"},"config":{"verb":"lock","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"unlock","condition":{"mode":"if_equals","option":"__subcommand","value":"unlock"},"config":{"verb":"unlock","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"limit","condition":{"mode":"if_equals","option":"__subcommand","value":"limit"},"config":{"verb":"limit","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"transfer","condition":{"mode":"if_equals","option":"__subcommand","value":"transfer"},"config":{"verb":"transfer","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"extend","condition":{"mode":"if_equals","option":"__subcommand","value":"extend"},"config":{"verb":"extend","allow_moderators":true}},{"type":"MANAGE_MANAGED_CHANNEL","group":"delete","condition":{"mode":"if_equals","option":"__subcommand","value":"delete"},"config":{"verb":"delete","allow_moderators":true}}]}',
    updated_at = CURRENT_TIMESTAMP
WHERE guild_id = '__built_in__' AND name = 'room';
