/**
 * Stats Widget Image API
 *
 * GET /api/stats/[guildId]/widget?type=voice_time&period=30d&t=TIMESTAMP&sig=SIGNATURE
 * via HMAC-signed URLs generated by the /stats command handler.
 *
 * Query params:
 *   type   - Widget type: any key in WIDGET_TYPES
 *   period - Time period: 7d, 30d (default: 30d)
 *   t      - Unix timestamp (for URL expiry & cache-busting)
 *   sig    - HMAC-SHA256 signature over guildId|type|period|t
 */

import { error } from '@sveltejs/kit';
import { generateWidget, WIDGET_TYPES, signWidgetUrl } from '$lib/stats-widget.js';
import { svgToPng, getAvatarBase64 } from '$lib/svg-to-png.js';
import {
	getMemberGrowthChart,
	getMessageActivityChart,
	getVoiceActivityChart,
	runStatsAggregation,
} from '$lib/db/stats-aggregation.js';
import { getLatestServerStats } from '$lib/db/server-stats.js';
import { log } from '$lib/log.js';

const VALID_TYPES = new Set(Object.keys(WIDGET_TYPES));
const VALID_PERIODS = new Set(['7d', '30d']);
const MAX_AGE_SECONDS = 300; // Signed URLs expire after 5 minutes

function getEnv(platform, name) {
	return (
		(platform as any)?.env?.[name] ??
		(typeof process !== 'undefined' ? process.env?.[name] : undefined)
	);
}

/**
 * Verify the HMAC signature on the widget URL.
 */
async function verifySignature(guildId, type, period, timestamp, signature, secret) {
	// Check expiry
	const now = Math.floor(Date.now() / 1000);
	if (Math.abs(now - Number(timestamp)) > MAX_AGE_SECONDS) {
		return false;
	}

	const expected = await signWidgetUrl(guildId, type, period, timestamp, secret);
	return expected === signature;
}

/** @type {import('./$types').RequestHandler} */
export async function GET({ params, url, platform }) {
	const { guildId } = params;

	// Validate guild ID format
	if (!/^\d{17,20}$/.test(guildId)) {
		throw error(400, 'Invalid guild ID');
	}

	const type = url.searchParams.get('type') || 'voice_time';
	const period = url.searchParams.get('period') || '30d';
	const timestamp = url.searchParams.get('t');
	const signature = url.searchParams.get('sig');

	if (!VALID_TYPES.has(type)) {
		throw error(400, `Invalid type. Must be one of: ${[...VALID_TYPES].join(', ')}`);
	}
	if (!VALID_PERIODS.has(period)) {
		throw error(400, 'Invalid period. Must be 7d or 30d');
	}

	// Verify HMAC signature
	const secret = getEnv(platform, 'DISCORD_PUBLIC_KEY');
	if (!secret || !timestamp || !signature) {
		throw error(401, 'Unauthorized');
	}

	const valid = await verifySignature(guildId, type, period, timestamp, signature, secret);
	if (!valid) {
		throw error(401, 'Invalid or expired signature');
	}

	// Fetch stats data
	const db = (platform as any)?.env?.DB;
	if (!db) {
		throw error(503, 'Database not available');
	}

	try {
		// Ensure aggregation is up-to-date
		await runStatsAggregation(db, guildId, { repair: false }).catch((err) => {
			log.warn(`[Widget] Aggregation failed for ${guildId}:`, err);
		});

		const widgetData: Record<string, any> = {};

		if (type === 'voice_time' || type === 'voice_users' || type === 'voice_peak') {
			widgetData.voiceActivityChartData = await getVoiceActivityChart(db, guildId, period);
		} else if (
			type === 'member_count' ||
			type === 'member_growth' ||
			type === 'member_joins' ||
			type === 'member_leaves' ||
			type === 'member_net_change'
		) {
			widgetData.memberGrowthChartData = await getMemberGrowthChart(db, guildId, period);
			if (type === 'member_count') {
				const latest = await getLatestServerStats(db, guildId);
				widgetData.currentMemberCount = latest?.human_count ?? latest?.member_count ?? 0;
			}
		} else if (type === 'message_count' || type === 'message_users') {
			widgetData.messageActivityChartData = await getMessageActivityChart(
				db,
				guildId,
				period
			);
		}

		// Generate SVG
		const avatarBase64 = await getAvatarBase64(url.origin);
		const svg = generateWidget(type, widgetData, { avatarBase64 });

		// Convert to PNG
		const origin = url.origin;
		const pngData = await svgToPng(svg, origin);

		return new Response(pngData as any, {
			headers: {
				'Content-Type': 'image/png',
				'Cache-Control': 'public, max-age=60',
				'Content-Disposition': 'inline; filename="stats-widget.png"',
			},
		});
	} catch (err) {
		log.error('[Widget] Failed to generate widget image:', err);
		throw error(500, 'Failed to generate widget image');
	}
}
